// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3ESxvZlK-uT-f52bvv3pSEe2T06-2ek',
    appId: '1:478231749796:web:f7d63031c3a6b4983bf231',
    messagingSenderId: '478231749796',
    projectId: 'chat-bloc-b2471',
    authDomain: 'chat-bloc-b2471.firebaseapp.com',
    storageBucket: 'chat-bloc-b2471.appspot.com',
    measurementId: 'G-Z7E739SYPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGWsRoQmwd-I84DtafgMk0nOdvw_qz40',
    appId: '1:478231749796:android:f0b7c004b12082233bf231',
    messagingSenderId: '478231749796',
    projectId: 'chat-bloc-b2471',
    storageBucket: 'chat-bloc-b2471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCboPAsS5z2QQVGzXWQYhJWtngOShi76Oc',
    appId: '1:478231749796:ios:e5d82e347e0b58e13bf231',
    messagingSenderId: '478231749796',
    projectId: 'chat-bloc-b2471',
    storageBucket: 'chat-bloc-b2471.appspot.com',
    iosBundleId: 'com.chatappbloc.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCboPAsS5z2QQVGzXWQYhJWtngOShi76Oc',
    appId: '1:478231749796:ios:8f6173339816a2ed3bf231',
    messagingSenderId: '478231749796',
    projectId: 'chat-bloc-b2471',
    storageBucket: 'chat-bloc-b2471.appspot.com',
    iosBundleId: 'com.example.stateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu3ESxvZlK-uT-f52bvv3pSEe2T06-2ek',
    appId: '1:478231749796:web:0178d8e067ceb47c3bf231',
    messagingSenderId: '478231749796',
    projectId: 'chat-bloc-b2471',
    authDomain: 'chat-bloc-b2471.firebaseapp.com',
    storageBucket: 'chat-bloc-b2471.appspot.com',
    measurementId: 'G-E8GWEYFF2F',
  );
}
